[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_pgsql", "php84Extensions.pgsql", "php84Extensions.gd", "php84Extensions.zip", "php84Extensions.intl", "php84Extensions.dom", "php84Extensions.xml", "nodejs_22"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci"]

[phases.build]
cmds = ["npm run build", "php artisan storage:link", "php artisan optimize"]
